name = "Ginkgo"
uuid = "4c8bd3c9-ead9-4b5e-a625-08f1338ba0ec"
authors = ["You Wu"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
